name: build_appimage

on: workflow_dispatch

jobs:

  build_appimage:
    name: build_appimage

    runs-on: 'ubuntu-20.04'
    strategy:

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build appimage
        run: |
          bash tools/build_appimage --version=${{ github.ref_name }} --jsonfile=tools/linux_libs.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: BeeRef*.appimage
          retention-days: 5
