name: build

on: workflow_dispatch

jobs:

  build:
    name: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-10.15', 'windows-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .
      - name: Run build.py
        run: |
          python build.py
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/*.zip
          retention-days: 5
