name: pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11']
        pyqt-version: ['6.4.0', '6.6.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libgl1-mesa-glx libegl1 libglib2.0-0 libxcb-image0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 xserver-xephyr libfontconfig1 libxkbcommon-dev libdbus-1-3 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libxcb-cursor0
          sudo apt install xvfb
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements/test.txt
          pip install pyQt6==${{ matrix.pyqt-version }} pyQt6-Qt6==${{ matrix.pyqt-version }} --upgrade
      - name: Run Unittests with pytest
        run: |
          xvfb-run --auto-servernum --server-num=1 --server-args="-screen 1 1920x1200x24 -ac +extension GLX" pytest --cov --cov-report=xml
      - name: Upload Coverage report to Codecov
        uses: codecov/codecov-action@v3
