name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install libgl1-mesa-glx libegl1 libglib2.0-0 libxcb-image0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1-dev xserver-xephyr libfontconfig1 libxkbcommon-dev libdbus-1-3
        sudo apt install xvfb
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements/dev.txt
    - name: Run Unittests with pytest
      run: |
        xvfb-run coverage run --source=beeref -m pytest -v -s
    - name: Upload Coverage report to Codecov
      uses: codecov/codecov-action@v1
